version: '3.8'

services:
  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: mixologue_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mixologue}
      - POSTGRES_USER=${POSTGRES_USER:-mixologue_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mixologue123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: mixologue_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Application Django
  web:
    build: .
    container_name: mixologue_web
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-mixologue_user}:${POSTGRES_PASSWORD:-mixologue123}@db:5432/${POSTGRES_DB:-mixologue}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8001

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: